---
title: "Getting POG and rrvgo"
output: 
  html_notebook:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r}
library(hgu133plus2.db)
library(GOSemSim)
library(org.Hs.eg.db)
library(rrvgo)
library(tidyverse)
library(ggsci)
```


```{r}
keytypes(hgu133plus2.db)
```



# Get POG

```{r}
limma_dataset_1 <- read_csv("dataframe_files/limma_dataset1_topgenes.csv")
glimpse(limma_dataset_1)
```



```{r}
limma_dataset_1_gene_list <- mapIds(x = hgu133plus2.db, keys = limma_dataset_1$PROBEID, 
       keytype = "PROBEID", column = "ENTREZID")

head(limma_dataset_1_gene_list)
```

```{r}
limma_dataset_1_gene_list %>% 
  unique() %>%
  length()
limma_dataset_1_gene_list <- limma_dataset_1_gene_list[!is.na(limma_dataset_1_gene_list)] %>% 
  unique()
limma_dataset_1_gene_list %>% 
  unique() %>%
  length()
```


```{r}
limma_dataset_1_gene_list %>% 
  enframe(name = "ProbeID", value = "ENTREZID") %>% 
  write_csv("dataframe_files/limma_dataset_1_DEG_entrez.csv")
  
```


```{r}
limma_dataset_2 <- read_csv("dataframe_files/limma_dataset2_topgenes.csv")
glimpse(limma_dataset_2)
```



```{r}
limma_dataset_2_gene_list <- mapIds(x = hgu133plus2.db, 
                                    keys = limma_dataset_2$ID, 
                                    keytype = "PROBEID", 
                                    column = "ENTREZID")

head(limma_dataset_2_gene_list)
```

```{r}
limma_dataset_2_gene_list %>% 
  unique() %>%
  length()
limma_dataset_2_gene_list <- limma_dataset_2_gene_list[!is.na(limma_dataset_2_gene_list)] %>% 
  unique()
limma_dataset_2_gene_list %>% 
  unique() %>%
  length()
```


```{r}
limma_dataset_2_gene_list %>% 
  enframe(name = "ProbeID", value = "ENTREZID") %>% 
  write_csv("dataframe_files/limma_dataset_2_DEG_entrez.csv")
  
```


```{r}
length(limma_dataset_1_gene_list) + length(limma_dataset_2_gene_list)
```


```{r}
intersect(limma_dataset_1_gene_list, limma_dataset_2_gene_list) %>% 
  length()
```


```{r}
setdiff(limma_dataset_1_gene_list, limma_dataset_2_gene_list) %>% 
  length()
```


```{r}
gfs_dataset_1 <- read_csv("dataframe_files/GFS_dataset1_topgenes.csv")
glimpse(gfs_dataset_1)
```


```{r}
gfs_dataset_1_gene_list <- mapIds(x = hgu133plus2.db, 
                                    keys = gfs_dataset_1$Probe, 
                                    keytype = "PROBEID", 
                                    column = "ENTREZID")

head(gfs_dataset_1_gene_list)
```


```{r}
gfs_dataset_1_gene_list %>% 
  unique() %>%
  length()
gfs_dataset_1_gene_list <- gfs_dataset_1_gene_list[!is.na(gfs_dataset_1_gene_list)] %>% 
  unique()
gfs_dataset_1_gene_list %>% 
  unique() %>%
  length()
```


```{r}
gfs_dataset_1_gene_list %>% 
  enframe(name = "ProbeID", value = "ENTREZID") %>% 
  write_csv("dataframe_files/gfs_dataset_1_DEG_entrez.csv")
  
```


```{r}
gfs_dataset_2 <- read_csv("dataframe_files/GFS_dataset2_topgenes.csv")
glimpse(gfs_dataset_2)
```



```{r}
gfs_dataset_2_gene_list <- mapIds(x = hgu133plus2.db, 
                                    keys = gfs_dataset_2$Probe, 
                                    keytype = "PROBEID", 
                                    column = "ENTREZID")

head(gfs_dataset_2_gene_list)
```


```{r}
gfs_dataset_2_gene_list %>% 
  unique() %>%
  length()
gfs_dataset_2_gene_list <- gfs_dataset_2_gene_list[!is.na(gfs_dataset_2_gene_list)] %>% 
  unique()
gfs_dataset_2_gene_list %>% 
  unique() %>%
  length()
```


```{r}
gfs_dataset_2_gene_list %>% 
  enframe(name = "ProbeID", value = "ENTREZID") %>% 
  write_csv("dataframe_files/gfs_dataset_2_DEG_entrez.csv")
  
```


```{r}
intersect(gfs_dataset_1_gene_list, gfs_dataset_2_gene_list) %>% 
  length()
```

```{r}
setdiff(gfs_dataset_2_gene_list, gfs_dataset_1_gene_list) %>% 
  length()
```


```{r}
gfs_dataset_1_gene_list %>% 
  unique() %>% 
  length()
```


```{r}
get_POG <- function(gene_list_1, gene_list_2, dataset_1, dataset_2){
  list_length_1 <- length(gene_list_1)
  list_length_2 <- length(gene_list_2)
  k <- length(intersect(gene_list_1, gene_list_2))
  df <- tibble("Dataset" = c(dataset_1, dataset_2),
                   "List Size" = c(list_length_1, list_length_2),
                   "Intersection Size" = rep(k, 2),
                   "POG Designation" = c("POG12", "POG21"), 
                   "Value" = c(k/list_length_1, k/list_length_2))
  return(df)
}
```


```{r}
limma_pog <- get_POG(limma_dataset_1_gene_list, limma_dataset_2_gene_list, "GSE76275", "GSE43358")

limma_pog %>% 
  group_by(`Intersection Size`) %>% 
  mutate(Average = mean(Value))

limma_pog %>% 
  write_csv("dataframe_files/limma_percentage_of_overlapping_genes.csv")
```


```{r}
gfs_pog <- get_POG(gfs_dataset_1_gene_list, gfs_dataset_2_gene_list, "GSE76275", "GSE43358")

gfs_pog %>% 
  group_by(`Intersection Size`) %>% 
  mutate(Average = mean(Value))

gfs_pog %>% 
  write_csv("dataframe_files/GFS_percentage_of_overlapping_genes.csv")
```

# Using rrvgo


```{r}
gfs_go_dataset_1 <- read_csv("dataframe_files/ora_gfs_dataset1.csv")

glimpse(gfs_go_dataset_1)
```


```{r}
gfs_go_dataset_2 <- read_csv("dataframe_files/ora_gfs_dataset2.csv")

glimpse(gfs_go_dataset_2)
```


```{r}
limma_go_dataset_1 <- read_csv("dataframe_files/ora_limma_dataset1.csv")

glimpse(limma_go_dataset_1)
```


```{r}
limma_go_dataset_2 <- read_csv("dataframe_files/ora_limma_dataset2.csv")

glimpse(gfs_go_dataset_2)
```


```{r}
sem_sim <- GOSemSim::godata(OrgDb = org.Hs.eg.db, ont = "BP", keytype = "GO")
```



```{r}
gfs_go_dataset_1.simMatrix <- calculateSimMatrix(gfs_go_dataset_1$term_id,
                                orgdb="org.Hs.eg.db",
                                ont="BP",
                                method="Rel", 
                                semdata = sem_sim)
```


```{r}
gfs_go_dataset_1.reduced <- reduceSimMatrix(gfs_go_dataset_1.simMatrix,
                threshold=0.7,
                orgdb="org.Hs.eg.db")

```


```{r}
treemapPlot(gfs_go_dataset_1.reduced)
```


```{r}
png(filename="plots/gfs_dataset_1_treemap.png",width=800, height=800)
treemapPlot(gfs_go_dataset_1.reduced)
dev.off()
```



```{r}
gfs_go_dataset_2.simMatrix <- calculateSimMatrix(gfs_go_dataset_2$term_id,
                                orgdb="org.Hs.eg.db",
                                ont="BP",
                                method="Rel", 
                                semdata = sem_sim)
```


```{r}
gfs_go_dataset_2.reduced <- reduceSimMatrix(gfs_go_dataset_2.simMatrix,
                threshold=0.7,
                orgdb="org.Hs.eg.db")

```


```{r}
treemapPlot(gfs_go_dataset_2.reduced)
```


```{r}
png(filename="plots/gfs_dataset_2_treemap.png",width=800, height=800)
treemapPlot(gfs_go_dataset_2.reduced)
dev.off()
```


```{r}
limma_go_dataset_1.simMatrix <- calculateSimMatrix(limma_go_dataset_1$term_id,
                                orgdb="org.Hs.eg.db",
                                ont="BP",
                                method="Rel", 
                                semdata = sem_sim)
```


```{r}
limma_go_dataset_1.reduced <- reduceSimMatrix(limma_go_dataset_1.simMatrix,
                threshold=0.7,
                orgdb="org.Hs.eg.db")

```


```{r}
treemapPlot(limma_go_dataset_1.reduced)
```

```{r}
png(filename="plots/limma_dataset_1_treemap.png",width=800, height=800)
treemapPlot(limma_go_dataset_1.reduced)
dev.off()
```


```{r}
limma_go_dataset_2.simMatrix <- calculateSimMatrix(limma_go_dataset_2$term_id,
                                orgdb="org.Hs.eg.db",
                                ont="BP",
                                method="Rel", 
                                semdata = sem_sim)
```



```{r}
limma_go_dataset_2.reduced <- reduceSimMatrix(limma_go_dataset_2.simMatrix,
                threshold=0.7,
                orgdb="org.Hs.eg.db")
```


```{r}
treemapPlot(limma_go_dataset_2.reduced)
```

```{r}
png(filename="plots/limma_dataset_2_treemap.png",width=800, height=800)
treemapPlot(limma_go_dataset_2.reduced)
dev.off()
```


```{r}
mdata_dataset_2 <- read_csv("dataframe_files/metadata_subset_GSE43358.csv")
```


```{r}
mdata_dataset_2 %>% 
  count(triple_negative_status)
```

